spring.application.name=notifyhub-api
server.port=${API_PORT}

# =================================
# POSTGRESQL Database Configuration
# ================================== 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===================
# REDIS Configuration
# ===================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASS}

# Timeout
spring.data.redis.timeout=2000

# ======================
# RABBITMQ Configuration
# ======================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.port=${RABBITMQ_PORT}

# Virtual Host
spring.rabbitmq.virtual-host=/

# Publisher confirms
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

# Consumer configuration
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=10

# ===================================
# ACTUATOR + PROMETHEUS Configuration
# ===================================
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator

# Prometheus format
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Health check configuration
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=when-authorized
management.endpoint.prometheus.enabled=true

management.health.db.enabled=true
# LOGGING Configuration
# =====================
logging.level.org.springframework=INFO
logging.level.com.github.tluccas.notifyhub=DEBUG
